{
 "title": "NYTaxi predictions monitoring",
 "time": { "from": "2024-02-24T16:58:02.116Z", "to": "2024-04-03T01:35:52.885Z" },
 "panels": [
  {
   "title": "Predictions drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM nytaxi_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share of missing values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", share_missing_values FROM nytaxi_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Correlations for column 'fare_amount' to 'passenger_count'",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", pearson_corr_passenger_count FROM nytaxi_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "'fare_amount' 0.5 Quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", fare_amount_0_5_quantile FROM nytaxi_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of drifted columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", num_drifted_columns FROM nytaxi_metrics LIMIT 50 "
    }
   ]
  }
 ]
}